### ISSUE TITLE
How can I start steganography?

### ISSUE THREAD

**Issue by Skandinaviske** [metallurgical/LSB-steganography-java#1]
There are just two choose file without a start button?
And whether your java project can choose file such as .jpg,.png or bmp
Help me,thx a lot

**Comment by metallurgical** [comment]
You can follow the instruction i create inside jsfiddle snippet.

There is no start button. The flow is simple:

1) Step 1 - Choose any .txt file containing a few words inside.
2) Step 2 - Choose cover image(to hide our data from step 1 into image(from this step)
3) Step 3 - Click button "Hide data into image"
4) Step 4 - Right click on image, and save the image(this image is the 2nd image shown on page which is containing our data we pick from step 1, the data was hidden inside)
5) Step 5 - After saving image(from step 4), choose back image that we saved(from step 4). The data(that reside on image) will automatically downloaded to your pc and you should see the downloaded file contain same result with the data from step 1).

** This step actually for another steganography([javascript](https://github.com/metallurgical/LSB-steganography-javascript))

p/s: Actually all the process was initiated automatically when you pick the file, click the button, etc.. 
p/p/s: Java code is not finished yet. Still work in progress :). But you can create your own library using any language you like

**Comment by Skandinaviske** [comment]
Thx for your help,I am a new hand in this area,I'll try my best to learn about your code
But this is no  button "Hide data into image"...

**Comment by metallurgical** [comment]
I mean, on the [jsfiddle](https://jsfiddle.net/norlihazmeyGhazali/quo42a2n/), should have "Hide data into image". Much welcome :)
